jadwal/urls.py
from django.urls import path
from . import views

app_name = 'jadwal'
urlpatterns = [
    # path('', views.jadwal_view, name="jadwal_view"),
    path('', views.jadwal_create, name="jadwal_create"),
    path('delete/<id>/', views.jadwal_delete, name="jadwal_delete")
]

stories/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webprofile.urls")),
    path('schedule/', include("jadwal.urls"))
]

webprofile/urls.py
from django.urls import path
from . import views

app_name = 'webprofile'
urlpatterns = [
    path('', views.index, name="profile"),
    path('bonus/', views.bonus, name="bonus")
]

jadwal/models.py
from django.db import models
import django.utils.timezone

# Create your models here.
class Jadwal(models.Model):
    KATEGORI = [
    ('urgent', 'urgent'),
    ('event', 'event'),
    ('personal', 'personal')
]

    judul_jadwal = models.CharField(max_length=100)
    tempat = models.CharField(max_length=100, null=True)
    kategori = models.CharField(
        max_length=8,
        choices=KATEGORI,
        default='personal',
    )
    # date_time = models.DateTimeField(auto_now_add = False, default = django.utils.timezone.now)
    date = models.DateField(auto_now_add = False, default = django.utils.timezone.now)
    day = models.CharField(max_length=10, default=None, null=True)
    time = models.TimeField(auto_now_add = False, default = django.utils.timezone.now)



    description = models.CharField(max_length=100, default = "")

    def __str__(self):
        return self.judul_jadwal

webprofile/models.py
import datetime
import django.utils.timezone
from django.db import models

# Create your models here.

jadwal/forms.py
from django import forms
from . import models
from django.utils import timezone
from datetime import datetime

class TimeInput(forms.TimeInput):
    input_type = "time"

class DateInput(forms.DateInput):
    input_type = "date"
    input_formats = ['%d %b %Y']


class CreateJadwal(forms.ModelForm):
    class Meta:
        model = models.Jadwal
        fields = ['judul_jadwal', 'tempat', 'kategori', 'date', 'time', 'description']

        widgets = {
            "time": TimeInput,
            "date": DateInput
        }

        
# class CreateJadwal(forms.Form):
#     judul_jadwal = forms.CharField(max_length=50)
#     tempat = forms.CharField(max_length=100)
#     tempat = forms.ChoiceField(max_length=100)
#     date = forms.DateField(required=False, initial= timezone.now, widget= DateInput(format='%d/%m/%Y'),input_formats=('%d/%m/%Y'))
#     time = forms.TimeField(required=False, widget=TimeInput)
#     description = forms.CharField(max_length=100, required=False)

jadwal/views.py
from django.shortcuts import render, redirect
from . import forms
from .models import Jadwal

# Create your views here.

def jadwal_create(request):
    if request.method == "POST":
        form = forms.CreateJadwal(request.POST)

        if form.is_valid():   
            jadwal_baru = form.save(commit=False)
            jadwal_baru.day = jadwal_baru.date.strftime("%A")
            jadwal_baru.save()
        
        return redirect("jadwal:jadwal_create")
    else:
        form = forms.CreateJadwal()
        return render(request, "jadwal/jadwal_create.html", {"form" : form, "schedules": Jadwal.objects.all().order_by("date")})

def jadwal_delete(request, id):
    jadwal = Jadwal.objects.get(id=id)
    jadwal.delete()
    return redirect("jadwal:jadwal_create")

webprofile/views.py
from django.shortcuts import render
from datetime import datetime, date


# Enter your name here
title = 'Kefas Satrio' # TODO Implement this
mhs_name = "Kefas Satrio Bangkit Solideantyo"
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2000, 4, 24) #TODO Implement this, format (Year, Month, Date)
npm = 1806204972 # TODO Implement this
universitas = "Universitas Indonesia"
# Create your views here.
def index(request):
    response = {'title': title, 'full_name': mhs_name, 'age': calculate_age(birth_date.year), 'npm': npm, 'universitas': universitas}
    return render(request, 'index.html', response)

def bonus(request):
    return render(request, 'bonus.html', {'title': "F.A.Q."})

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:100i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300i&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{% static '/images/kefas-logo-white.svg' %}">
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <link href="{% static 'bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <link href="{% static 'jadwal.css' %}" rel="stylesheet">


    <!-- buat form datetimefield jadwal -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />
    
    <title>{{ title }}</title>
</head>
<body>
    <!--BUKAN BOOTSTRAP (maybe for later) -->
    <!-- <nav id="nav">
        <a href="#landing"><img id="logo" src="{% static '/images/kefas-logo-red.svg' %}"></a>
        <div class="navi">
            <a href="#about"><p class="navtext">About me</p></a>
            <a href="#experiences"><p class="navtext">Experiences</p></a>
            <a href="#tools"><p class="navtext">Tools</p></a>
            <a href="#contact"><p class="navtext">Contact</p></a>
            <a href="#gallery"><p class="navtext">Gallery</p></a>
        </div>
            
    </nav> -->


    <nav id="nav" class="navbar navbar-expand-md fixed-top p-0 pr-3">
        <a class="navbar-brand" href="{% url 'webprofile:profile' %}#landing"><img class="m-0 ml-3" id="logo" src="{% static '/images/kefas-logo-red.svg' %}"></a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#collapse_target">
            <img class="navbar-toggler-icon" src="{% static '/images/burger.svg' %}">
        </button>
        <div class="collapse navbar-collapse" id="collapse_target">
          <ul class="navbar-nav ml-auto">
              <li class="nav-item ml-auto">
                <a class="nav-link navtext" href= "{% url 'webprofile:profile' %}#about">About me </a>
              </li>
              <li class="nav-item ml-auto">
                <a class="nav-link navtext" href="{% url 'webprofile:profile' %}#tools">Tools</a>
              </li>
              <li class="nav-item ml-auto">
                <a class="nav-link navtext" href="{% url 'webprofile:profile' %}#experiences">Experiences</a>
              </li>
              <li class="nav-item ml-auto">
                <a class="nav-link navtext" href="{% url 'webprofile:profile' %}#contact">Contact</a>
              </li>
              <li class="nav-item ml-auto">
                <a class="nav-link navtext" href="{% url 'webprofile:profile' %}#gallery">Gallery</a>
              </li>
              <li class="nav-item ml-auto">
                  <a class="nav-link navtext" href="{% url 'webprofile:bonus' %}">Bonus Page</a>
                </li>
            </ul>
        </div>
        
    
      </nav>

      {% block content %}
      {% endblock %}
</body>
<script src="{% static '/scripts/navbar.js' %}"></script>
</html>

templates/bonus.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="bonus-body">
    <!-- <div class="top"><a href="{% url 'webprofile:profile' %}"><div class="back"><h1>Get back</h1></div></a></div> -->
    <div class="warning">
        <h1>WARNING</h1>
        <h5>Scroll only if you understand Bahasa Indonesia (◡ w ◡)</h5>
    </div>
    <div class="transition transition-bonus"></div>
    <div class="section bottom">
            <h1>F.A.Q</h1>
            <h2>Kefas, Kefas apa yang bikin adem?</h2>
                <img src="https://www.static-src.com/wcsstore/Indraprastha/images/catalog/medium//93/MTA-1643457/cosmos_cosmos-16sdb-stand-fan--16-inch-_full02.jpg" style="height:60%; width:60%;">
                <p><i>Kefas angin</i></p>
            
            <h2>Kefas, Kefas apa yang lembut?</h2> 
                <img src= "https://img.okeinfo.net/content/2015/04/13/194/1133181/intip-manfaat-bola-kapas-bagi-kecantikan-yIPtVeEtHS.jpg" style="height: 60%; width: 60%;">
                <p><i>Kepas</i></p>
            
                <h2>Apa yang terjadi bila Kefas ditaruh di ruangan bersuhu tinggi?</h2> 
                <img src="https://asset.kompas.com/crop/2x3:998x667/750x500/data/photo/2017/07/05/1117909854.jpg" style="height: 60%; width: 60%;">
                <p><i>Kefanasan</i></p>
            
            <h2>Kemanakah Kefas pergi jika ingin berbelanja?</h2>
                <img src="https://img.beritasatu.com/cache/beritasatu/910x580-2/141465633732.jpg" style="height: 60%; width: 60%;">
                <p><i>Kefasar</i></p>
        
    </div>
</div>



{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block content %}
    <div id="landing" class="landing">       
        <div class="landing-text">
                <h1 class="name">Kefas Satrio.</h1>
                <p class="short-desc">Graphic Designer. Software Engineer. Student.</p>
        </div>
    </div>

    <div class="transition1"></div>

    <div id="about" class="section about">
        <h1 class="title">About Me</h1>
        <div class="about-container">
            <img class="kefas" src="{% static '/images/kefas.PNG' %}" alt="kefas">
            <img class="two-circles" src="{% static '/containers/two-circles.svg' %}">
            <div class="info">
                <p>
                    <span>Hi, I'm Kefas.</span> <br>
                    An undergraduate student at Universitas Indonesia
                    currently studying computer science. I’m passionate 
                    about coding and I like to draw in my spare time.
                </p>
            </div>
            
        </div>
        <div class="hello">Hello there.</div>
       
    </div>

    <div class="transition transition2"></div>

    <div id="tools" class="section tools">
        <h1 class="title">Tools</h1>

        <div class="row">
            
        </div>
        <div class="toolset">    
            <div class="tool-list first-tools">   
                <p>HTML</p>
                <p>ReactJS</p>
                <p>Python</p>
                <p>Photoshop</p>
            </div>
            <div class="tool-list second-tools">  
                <p>CSS</p>
                <p>Django</p>
                <p>Java</p>
                <p>Figma</p>
            </div>
            <div class="tool-list third-tools">   
                <p>Git</p>
                <p>Django REST</p>
                <p>Javascript</p>
                <p>Trello</p>
            </div>
        </div>
        <p>Here are tools that I personally like to use from time to time</p>
    </div>

    <div class="transition transition3"></div>

    <div id="experiences" class="section experiences">
        <h1 class="title">Experiences</h1>
        <div class="experience-list">
                <div class="experience"><img src="{% static '/containers/dot.svg' %}" alt=""> <p>Staff of IT Development Department</p></div>
                <p class="experience-desc">Contributed in making websites for BEM PTI Fasilkom UI</p>

                <div class="experience"><img src="{% static '/containers/dot.svg' %}" alt=""> <p>Teaching Assistant of Programming Foundations 1 Course</p></div>
                <p class="experience-desc">Taught university students the basics of programming and assisted them on a weekly tutorial schedule</p>
                
                <div class="experience"><img src="{% static '/containers/dot.svg' %}" alt=""> <p>Mentor of Programming Foundations 0</p></div>
                <p class="experience-desc">Mentored a group of students who had no programming background
                        and taught them the basics of Python</p>
                
                <div class="experience"><img src="{% static '/containers/dot.svg' %}" alt=""> <p>Staff of Business-IT Case Competition</p></div>
                <p class="experience-desc">Contributed in making an IT-related business case for a large competition 
                        held by Compfest11 in Universitas Indonesia</p>
                
                <div class="experience"><img src="{% static '/containers/dot.svg' %}" alt=""> <p>Software Engineer for Lytebox</p></div>
                <p class="experience-desc">Contributed in the making of the Lytebox website as a frontend developer</p>
            </div>
        <div class="git">
            <a href="https://github.com/kefassatrio" target="_blank"><img src="{% static '/images/github.svg' %}"></a>
            <a href="https://gitlab.com/kefassatrio" target="_blank"><img src="{% static '/images/gitlab.svg' %}"></a>
        </div>
    </div>
    <div class="transition transition4"></div>
    <div id="contact" class="section contact">
        <h1 class="title2">Get in touch</h1>
        <div class="line"></div>
        <a href="https://www.linkedin.com/in/kefas-satrio-bangkit-solideantyo-58b43a17b/" target="_blank"><img onclick="linkedin.com" class="linkedin" src="{% static '/images/linkedin.svg' %}"></a>
        <div class="email">
            <p>kefassatrio@gmail.com</p>
        </div>
        <div class="line-sosmed">
            <img src="{% static '/images/line.svg' %}">
            <p>@cephas_knight</p>
        </div>
    </div>
    <div class="transition5">
        <p>Many more works and projects are coming up!</p>
        <p>But for now, just take a look at some of my artworks below</p>
    </div>
    <div id="gallery" class="section gallery">
        <div class="title2">Art Gallery</div>
        <div class="line"></div>
        <img class="art" src="{% static '/images/Artworks/woof.svg' %}">
        <img class="art" src="{% static '/images/Artworks/experiment1.svg' %}">
        <img class="art" src="{% static '/images/Artworks/experiment2.svg' %}">
        <img class="art" src="{% static '/images/Artworks/web-po.svg' %}">
        <img class="art" src="{% static '/images/Artworks/cheo.svg' %}">
        <img class="masmas" src="{% static '/images/Artworks/masmas.svg' %}">
        <h1 class="title2">Thank you for visiting</h1>
        <div class="line line-end"></div>
        <p class="title2 end">Have a nice day</p>
        <p class="more">still want to see more? click <a href="{% url 'webprofile:bonus' %}">here</a></p>
    </div>
    
{% endblock %}

templates/jadwal/jadwal_create.html
{% extends 'base.html' %}
{% block content %}
    <!-- <div class="create-jadwal">
        <h1>Make a schedule:</h1>
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                            <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1"/>
                            <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                            </div>
                        </div>
                    </div>
                </div>
                <script type="text/javascript">
                    $(function () {
                        $('#datetimepicker1').datetimepicker();
                    });
                </script>
            </div>
        </div> -->
        <div class="jadwal-section">
            <form class="site-form" action="" method="post">
                {% csrf_token %}
                <p>Title: {{ form.judul_jadwal }} </p>
                <!-- {{ form.date_time }} -->
                <p>Place: {{ form.tempat }}</p>
                <p>Category: {{ form.kategori }}</p>
                <p>Date: {{ form.date }}</p>
                <p>Time: {{ form.time }}</p>
                <p>Description: {{ form.description }}</p>
                <input class="butt" type="submit" value="add schedule"/>
            </form>
            <div class="semua-jadwal">
                {% for jadwal in schedules %}
                <div class="jadwal">
                    <div class="info-jadwal">
                        <p>Title: {{ jadwal.judul_jadwal }}</p>
                        <p>Category: {{ jadwal.kategori }}</p>
                        <p>Place: {{ jadwal.tempat }}</p>
                        <p>Day: {{ jadwal.day }}</p>
                        <p>Date: {{ jadwal.date }}</p>
                        <p>Time: {{ jadwal.time }}</p>
                        <p>Description: {{ jadwal.description }}</p>
                    </div>
                    <a href="{% url 'jadwal:jadwal_delete' id=jadwal.id %}"><button>delete</button></a>
                </div>
    
                {% endfor %}
            </div>
            
        </div>
{% endblock %}